defaults: &defaults
  gallery.s3bucket: ''
  gallery.gallery_dir: 'gallery'
  gallery.thumbnails.dir: 'thumbnails'
  gallery.thumbnails.size: '256x256'
  gallery.webview.dir: 'thumbnails'
  gallery.webview.size: '800x600'

development:
  <<: *defaults
  gallery.s3bucket: 'storage.photos.spstapleton.com'

test:
  <<: *defaults
  gallery.s3bucket: 'storage.photos.spstapleton.com'

production:
  <<: *defaults
  gallery.s3bucket: 'storage.photos.spstapleton.com'